### ISSUE TITLE
Unable to play video on mobile 

### ISSUE THREAD

**Issue by RiotTheClanker** [avoonix/.github#1]
### Expected Behavior

Play videos on mobile 

### Actual Behavior

Dose not play video
![IMG_1946](https://github.com/avoonix/.github/assets/87954311/2c9bc113-bc3b-492a-99f7-2eaa8a56bcd3)

### Steps to Reproduce the Problem

Attempt to play video on mobile 
(Using IPhone 14 Pro with Firefox app and the link being added to Home Screen)

**Comment by avoonix** [comment]
Hiya,
has the problem resolved itself or is this still an issue?

(it's not a huge problem, but the correct place for issues is [here](https://github.com/avoonix/material-e621/issues))

**Comment by RiotTheClanker** [comment]
There is still an issue, sorry.

Darren Lueders

**Comment by avoonix** [comment]
I now added the `playsinline` attribute to the video element. I don't have any apple devices so I can't test if that changes anything. 
Maybe this can narrow it down:
- Does it play on Mac OS devices?
- Does the same video on the original e621 site play?
- If you can access the browser console, are there any errors logged?

**Comment by RiotTheClanker** [comment]
I’m sorry but I do not have access to Mac OS, but o will certainly test it
on IPhone.

Darren Lueders

**Comment by RiotTheClanker** [comment]
I can confirm that it absolutely works on IPhone

Darren Lueders
